#!/bin/bash -l
#
# ++++ THIS IS A CYLC TASK JOB SCRIPT ++++
# Suite: ESDM-27-10-2020-4
# Task: ens_test2_jasmin_esdm.1
# Job log directory: 1/ens_test2_jasmin_esdm/01
# Job submit method: slurm
# Execution time limit: 600.0

# DIRECTIVES:
#SBATCH --job-name=ESDM-27-10-2020-4.ens_test2_jasmin_esdm.1
#SBATCH --output=/home/users/lucy/cylc-run/ESDM-27-10-2020-4/log/job/1/ens_test2_jasmin_esdm/01/job.out
#SBATCH --error=/home/users/lucy/cylc-run/ESDM-27-10-2020-4/log/job/1/ens_test2_jasmin_esdm/01/job.err
#SBATCH --time=10:00
#SBATCH --ntasks=16
#SBATCH --partition=par-multi
#SBATCH --chdir=/group_workspaces/jasmin4/ncas_cms/glister/esdm/slurm_chdir_test
export CYLC_DIR='/apps/jasmin/metomi/cylc-7.8.6'
export CYLC_VERSION='7.8.6'
CYLC_FAIL_SIGNALS='EXIT ERR XCPU'

cylc__job__inst__cylc_env() {
    # CYLC SUITE ENVIRONMENT:
    export CYLC_CYCLING_MODE="integer"
    export CYLC_SUITE_FINAL_CYCLE_POINT="1"
    export CYLC_SUITE_INITIAL_CYCLE_POINT="1"
    export CYLC_SUITE_NAME="ESDM-27-10-2020-4"
    export CYLC_UTC="False"
    export CYLC_VERBOSE="false"

    export CYLC_SUITE_RUN_DIR="/home/users/lucy/cylc-run/ESDM-27-10-2020-4"
    export CYLC_SUITE_DEF_PATH="${HOME}/xios-esdm-cylc"
    export CYLC_SUITE_DEF_PATH_ON_SUITE_HOST="/home/users/lucy/xios-esdm-cylc"
    export CYLC_SUITE_UUID="22a09d09-5988-473b-86ba-73419c7e6990"

    # CYLC TASK ENVIRONMENT:
    export CYLC_TASK_JOB="1/ens_test2_jasmin_esdm/01"
    export CYLC_TASK_NAMESPACE_HIERARCHY="root batch ens_test2_jasmin_esdm"
    export CYLC_TASK_DEPENDENCIES=""
    export CYLC_TASK_TRY_NUMBER=1
}

cylc__job__inst__user_env() {
    # TASK RUNTIME ENVIRONMENT:
    export XIOS_EXEC MODEL_EXEC INPUT_DATA_NML INPUT_DATA_NC NPROCX NPROCY NTIMES NUMENS LAUNCH_MPI_MODEL LAUNCH_MPI_XIOS
    XIOS_EXEC="/home/users/jcole/software/xios_trunk_r1870/config_GCC_LINUX_ESDM_dev/bin/xios_server.exe"
    MODEL_EXEC="/group_workspaces/jasmin4/ncas_cms/glister/esdm/jasmin_centos_7.7_gcc_9.1.0_esdm/xios_test"
    INPUT_DATA_NML="input_data_ens"
    INPUT_DATA_NC="/group_workspaces/jasmin4/ncas_cms/glister/esdm/jasmin_centos_7.7_gcc_9.1.0_esdm/u_plev_192x145x17.nc"
    NPROCX="2"
    NPROCY="2"
    NTIMES="6"
    NUMENS="3"
    LAUNCH_MPI_MODEL="-np 4"
    LAUNCH_MPI_XIOS="-np 4"
}

cylc__job__inst__init_script() {
# INIT-SCRIPT:
export SPACK_ROOT=/home/users/kunkel/spack
. $SPACK_ROOT/share/spack/setup-env.sh
spack load jansson glib gcc/aafm73y gettext/3bilnvc cmake autoconf/7qjzal7 automake/b7g5fr6 perl-uri
export MODULEPATH=$MODULEPATH:/home/users/kunkel/install/modules
module load kunkel/openmpi/3.1
module load kunkel/hdf5/1.10.6
export PATH=/home/users/jcole/esdm/install/bin:$PATH
export LIBRARY_PATH=/home/users/jcole/esdm/install/lib:$LIBRARY_PATH
export LD_LIBRARY_PATH=/home/users/jcole/esdm/install/lib:$LD_LIBRARY_PATH
export LD_RUN_PATH=/home/users/jcole/esdm/install/lib:$LD_RUN_PATH
export CPATH=/home/users/jcole/esdm/install/include:$CPATH
module list
}

cylc__job__inst__script() {
# SCRIPT:
/home/users/glister/ens_test2_jasmin_esdm.sh
}

. "${CYLC_DIR}/lib/cylc/job.sh"
cylc__job__main

#EOF: 1/ens_test2_jasmin_esdm/01
