#!/bin/bash -l
#
# ++++ THIS IS A CYLC TASK JOB SCRIPT ++++
# Suite: e1
# Task: broadcast-test.20220101T0000Z
# Job log directory: 20220101T0000Z/broadcast-test/01
# Job submit method: background
export CYLC_DIR='/apps/jasmin/metomi/cylc-7.8.6'
export CYLC_VERSION='7.8.6'
CYLC_FAIL_SIGNALS='EXIT ERR TERM XCPU'

cylc__job__inst__cylc_env() {
    # CYLC SUITE ENVIRONMENT:
    export CYLC_CYCLING_MODE="gregorian"
    export CYLC_SUITE_FINAL_CYCLE_POINT="20220101T0000Z"
    export CYLC_SUITE_INITIAL_CYCLE_POINT="20210101T0000Z"
    export CYLC_SUITE_NAME="e1"
    export CYLC_UTC="False"
    export CYLC_VERBOSE="false"

    export CYLC_SUITE_RUN_DIR="/home/users/lucy/cylc-run/e1"
    export CYLC_SUITE_DEF_PATH="${HOME}/puma/mock-example/eios-test"
    export CYLC_SUITE_DEF_PATH_ON_SUITE_HOST="/home/users/lucy/puma/mock-example/eios-test"
    export CYLC_SUITE_UUID="3896972d-5e09-4988-90fb-62d01fdf4258"

    # CYLC TASK ENVIRONMENT:
    export CYLC_TASK_JOB="20220101T0000Z/broadcast-test/01"
    export CYLC_TASK_NAMESPACE_HIERARCHY="root broadcast-test"
    export CYLC_TASK_DEPENDENCIES="post.20220101T0000Z"
    export CYLC_TASK_TRY_NUMBER=1
}

cylc__job__inst__script() {
# SCRIPT:
# BROADCAST=0 => the file is placed in the WORK directory
# BROADCAST=1 => the file is placed in the SHARE directory
	BROADCAST=0

# Test if previous file is in the WORK directory and save its size
        FILE=$CYLC_SUITE_WORK_DIR/$CYLC_TASK_CYCLE_POINT/model/b.txt
        if test -f "$FILE"; then
                SIZE=$(ls -l $FILE | cut -f5 -d " ")
        fi
echo "FILE=$FILE"

# Test if previous file is in the SHARE directory and save its size
	FILE=$CYLC_SUITE_SHARE_DIR/$CYLC_TASK_CYCLE_POINT/model/b.txt
	if test -f "$FILE"; then
		SIZE=$(ls -l $FILE | cut -f5 -d " ")
	fi
echo "FILE=$FILE"

# If the size is less than equal to the mean of all files,
# set BROADCAST to 1 and send the next file to SHARE

#	MEAN=$(< $CYLC_SUITE_RUN_DIR/post/mean.txt)
#	echo "DIR=$CYLC_SUITE_RUN_DIR/post/calc-mean.sh"
	echo "SIZE=$SIZE"
	MEAN=9000

	if [[ $SIZE -lt $MEAN ]]; then
		BROADCAST=1
	fi
	echo "BROADCAST=$BROADCAST"
        NEXT_CYCLE=$(cylc cycle-point --offset-years=1)
	# echo "NEXT_CYCLE = $NEXT_CYCLE"
	if [[ $BROADCAST == 1 ]]; then
	    cylc broadcast -n 'model' -s "[environment]VAR_DIR=$CYLC_SUITE_SHARE_DIR/$NEXT_CYCLE/model" "${CYLC_SUITE_NAME}"
echo "DIR=$CYLC_SUITE_SHARE_DIR/$NEXT_CYCLE/model"
	else
	            cylc broadcast -n 'model' -s "[environment]VAR_DIR=$CYLC_SUITE_WORK_DIR/$NEXT_CYCLE/model" "${CYLC_SUITE_NAME}"
	fi
}

. "${CYLC_DIR}/lib/cylc/job.sh"
cylc__job__main

#EOF: 20220101T0000Z/broadcast-test/01
